### ISSUE TITLE
Doesn't create output directory if missing

### ISSUE THREAD

**Issue by OrangeDog** [janssk1/maven-graph-plugin#6]
For example:
> [ERROR] Failed to execute goal com.github.janssk1:maven-dependencygraph-plugin:1.2:graph (default-cli) on project myproject: Can't write to file: C:\dev\myproject\target\myproject-1.5.0-SNAPSHOT-PACKAGE-deps.graphml (The system cannot find the path specified) -> [Help 1]

Is solved if the "target" directory is manually created.
The project may not output anything itself, so it shouldn't rely on another phase creating it.

**Comment by eniniz** [comment]
I'm having the same problem

**Comment by JPDSousa** [comment]
Same problem. It's a shame as this tool is quite promising, but for a giant multi-module project it is simply impractical to create all missing target folders.

By the way: the problem only seems to manifest in pom dependencies (i.e. not jar ones), as these are the modules who don't require a target folder.
